// Generated by https://quicktype.io

export interface Client {
    id:       string;
    isActive: boolean;
    picture:  string;
    age:      number;
    eyeColor: EyeColor;
    name:     string;
    gender:   Gender;
    company:  string;
    email:    string;
    phone:    string;
    address:  string;
}

export enum Gender {
    Female = "female",
    Male = "male",
}


export interface ClientsResponse {
    first: number;
    prev:  null;
    next:  number;
    last:  number;
    pages: number;
    items: number;
    data:  Client[];
}

export enum EyeColor {
    Blue = "blue",
    Brown = "brown",
}


